sudo: required
services:
  - docker
 
before_install:
  - docker build -t akhil/docker-react-aws -f Dockerfile.dev .
after_success: 
  -travis_wait 30 docker run 
script:

  - docker run akhil/docker-react-aws npm run test