install: travis_wait  mvn install
sudo: required
services:
  - docker
 
before_install:
  - docker build -t akhil/docker-react-aws -f Dockerfile.dev .
 
script:
  - docker run akhil/docker-react-aws npm run test