
language: node_js
os: linux
dist: xenial
node_js:
  - "7"
sudo: false

services:
  - docker

before_install:
  - docker build -t manforce001/docker-react -f Dockerfile.dev .

script:
  - docker run manforce001/docker-react npm run test -- --coverage
