sudo: required
services:
  - docker
 
before_install:
  - docker build -t akhil/docker-react-aws -f Dockerfile.dev .
 
install: travis_wait 30 mvn install
script:

  - docker run akhil/docker-react-aws npm run test